bookit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rooms.urls')),
]

handle404 = 'rooms.views.error_404_view'

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'
urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('handleLogin/', views.handleLogin, name='handleLogin'),
    path('handleSignup/', views.handleSignup, name='handleSignup'),
    path('handleRoom/', views.handleRoom, name='handleRoom'),
    path('logout/', views.handleLogout, name='logout'),
    path('view-rooms/', views.rooms, name='view-rooms'),
    path('<int:room_id>', views.room, name='room'),
    path('add-room/', views.addRoom, name='add-room'),
    path('<str:seller_id>', views.seller, name='seller')
]

rooms/models.py
from django.db import models


class Room(models.Model):
    # model for rooms
    def __str__(self) -> str:
        return self.address
    room_id = models.AutoField(primary_key=True)
    image = models.CharField(max_length=255, default="null")
    room_size = models.CharField(max_length=50)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=50)
    rate = models.IntegerField(default=0)
    floor = models.CharField(max_length=5, default="null")
    furnishing = models.CharField(max_length=25, default="null")
    area = models.CharField(max_length=50, default="null")
    parking = models.CharField(max_length=25, default="null")
    description = models.CharField(max_length=255)
    seller_id = models.CharField(default="null", max_length=20)

users/__pycache__/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomAccountManager


class MyUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(("email address"), unique=True)
    name = models.CharField(max_length=75)
    is_seller = models.BooleanField(default=False)
    contact = models.CharField(max_length=10)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomAccountManager


class MyUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(("email address"), unique=True)
    name = models.CharField(max_length=75)
    is_seller = models.BooleanField(default=False)
    contact = models.CharField(max_length=10)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.name

rooms/views.py
from django.http.response import Http404
from . import models
from django.shortcuts import render, redirect, HttpResponse
from users.models import MyUser
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib import messages
from .models import Room


def index(request):
    return render(request, "home.html")


def login(request):
    return render(request, "login.html")


def handleLogin(request):
    if request.method == 'POST':
        email = request.POST['email']
        pass1 = request.POST['pass']
        user = authenticate(email=email, password=pass1)
        if user is not None:
            auth_login(request, user)
            # print(user.actype)
            messages.success(request, "Successfully Logged In")
            return redirect('rooms:home')
        else:
            messages.error(request, "Invalid credentials, Try again")
            return redirect('rooms:login')
    else:
        messages.error(request, "Login First!")
        return redirect('rooms:login')


def signup(request):
    return render(request, "signup.html")


def handleSignup(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        actype = request.POST['ac-type']
        pass1 = request.POST['pass']
        pass2 = request.POST['pass2']
        contact = request.POST['contact']
        is_seller = False
        # check for inputs
        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('signup')
        if actype == 'seller':
            is_seller = True
        # add user to models
        myuser = MyUser.objects.create_user(
            email, name, contact, is_seller, pass1)
        myuser.save()

        # redirect user to homepage
        messages.success(
            request, "Your Book It account has been created, Login to continue")
        return redirect('rooms:login')
    else:
        messages.error(request, "Signup First!")
        return redirect('rooms:signup')


def handleLogout(request):
    logout(request)
    messages.success(request, "Successfully Logged out")
    return redirect("/")


def rooms(request):
    allrooms = Room.objects.all()
    forFrontend = {
        'rooms': allrooms
    }
    return render(request, "user/view-rooms.html", forFrontend)


def room(request, room_id):
    try:
        room = Room.objects.get(pk=room_id)
    except:
        raise Http404("Room Id Is Invalid!")
    return render(request, "user/room.html", {'room': room})


def seller(request, seller_id):
    try:
        seller = MyUser.objects.get(name=seller_id)
    except MyUser.DoesNotExist:
        raise Http404("Seller Does Not Exist")
    return render(request, "seller/seller.html", {'seller': seller})


def addRoom(request):
    return render(request, "seller/add-room.html")


def error_404_view(request):
    return render(request, "404.html")


def handleRoom(request):

    if request.method == 'POST':
        size = request.POST['room_size']
        image = request.POST['image']
        address = request.POST['address']
        city = request.POST['city']
        rate = request.POST['rate']
        floor = request.POST['floor']
        furnishing = request.POST['furnishing']
        area = request.POST['area']
        parking = request.POST['parking']
        description = request.POST['description']

        # check for inputs

        # add user to models
        newroom = models.Room.objects.create()
        newroom.image = image
        newroom.room_size = size
        newroom.address = address
        newroom.city = city
        newroom.rate = rate
        newroom.floor = floor
        newroom.furnishing = furnishing
        newroom.area = area
        newroom.parking = parking
        newroom.description = description
        newroom.seller_id = str(request.user.name)
        newroom.save()

        # redirect user to homepage
        messages.success(
            request, "Your Palce Have Been Successfully added")
        return redirect('rooms:home')
    else:
        messages.error(request, "Signin First!")
        return redirect('rooms:home')

users/__pycache__/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {%comment %} bootstrap cdns {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    {% comment %} my styles {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} favicon links {% endcomment %} 
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "assets/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "assets/favicon/favicon-16x16.png" %}">
     <link rel="manifest" href="{% static "assets/favicon/site.webmanifest" %}">
    <title>Book-IT</title>
  </head>
  <body>
    {% block nav %}
      {% include 'nav.html' %}
    {% endblock  %}
    {% comment %} message {% endcomment %}
    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
      <strong>!!</strong>
      {{ msg }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% comment %} end of message {% endcomment %}
    <div class="containr">
      {% block 404 %}
        {% comment %} 404 error page {% endcomment %}
      {% endblock  %}
      {% block home %}
        {% comment %} home page content {% endcomment %}
      {% endblock %}
      {% block signup %}
        {% comment %} signup page content {% endcomment %}
      {% endblock %}
      {% block login %}
        {% comment %} login page content {% endcomment %}
      {% endblock %}
      {% block rooms %}
        {% comment %} rooms page content {% endcomment %}
      {% endblock %}
      {% block room %}
        {% comment %} room page content {% endcomment %}
      {% endblock %}
      {% block seller %}
        {% comment %} seller page content {% endcomment %}
      {% endblock %}
      {% block addroom %}
        {% comment %} seller page content {% endcomment %}
      {% endblock %}
    {% if user.is_staff %}
      <a href="http://127.0.0.1:8000/admin/" class="float">
        admin
      </a>
    {% endif %}
    {% if user.is_seller %}
      <a href="http://127.0.0.1:8000/add-room/" class="float" style="left:20px;">
        add
      </a>
    {% endif %}
    </div>
    {% block footer %}
      {% include 'footer.html' %}
    {% endblock  %}
    {%comment %} bootstrap cdns {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
{% block footer %}
<footer>
  <a
    href="https://kushagra-aa.github.io/portfolio/"
    class="left"
    target="_blank"
    >kushagra-aa</a
  >
  <div class="center copy cap">&copy book it</div>
  <a
    href="https://github.com/kushagra-aa/bookit"
    class="right cap"
    target="_blank"
    >get code</a
  >
</footer>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block home %}
<section class="home">
  <div class="hero">
    <div class="tit">
      Welcome To
      <div class="bld">Book It</div>
    </div>
    <div class="in-hero">
      <div class="lt">
        <p class="cap">redefining house hunting!</p>
        <a href="view-rooms/">
          <button class="btn-acc-pri2 btn-home">
            Let’s find a home that’s perfect for you!
          </button>
        </a>
      </div>
      <div class="rt">
        <img
          src="{% static 'assets/media/illustrations/hero-floater.png' %}"
          class="hero-ill floater"
        />
        <img
          src="{% static 'assets/media/illustrations/hero-unfloater.png' %}"
          class="hero-ill unfloater"
        />
      </div>
    </div>
  </div>
  <div class="mid">
    <p>
      Here at Book It, we help you discover a place you'll love to live.
      <br />
      Directly contact the owner, no middle man required.
    </p>
  </div>
  <div class="sec">
    <div class="sec-cards">
      <div class="sec-card floating">
        <div class="sec-ill">
          <img
            src="{% static 'assets/media/illustrations/apartment-floater.png' %}"
            class="card-ill card-float floater"
          />
          <img
            src="{% static 'assets/media/illustrations/apartment-unfloater.png' %}"
            class="card-ill unfloater"
          />
        </div>
        <h3>Find Your Perfect Home</h3>
        <p>
          When you work with a real estate agent, you'll get selling support at
          every step, from prepping and listing your home to marketing that gets
          buyers in the door.
        </p>
      </div>
      <div class="sec-card floating">
        <div class="sec-ill">
          <img
            src="{% static 'assets/media/illustrations/roomtop-floater.png' %}"
            class="card-ill card-float floater"
          />
          <img
            src="{% static 'assets/media/illustrations/roomtop-unfloater.png' %}"
            class="card-ill unfloater"
          />
        </div>
        <h3>Rent A Home</h3>
        <p>
          We’re creating a seamless online experience – from shopping on the
          largest rental network, to applying, to paying rent.
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block login %}
<div class="login">
<div class="l">
<div class="log-reg-tit upca">
login
</div>
<div class="in-card">
<form action="/handleLogin/" method="POST" class="log-reg-form">
{% csrf_token %}
  <label for="email">Email</label>
  <input type="email" id="email" name="email" placeholder="Enter E-Mail" class="log-reg-in"/>
  <label for="pass">Password</label>
  <input type="password" id="pass" name="pass" placeholder="Enter Password" class="log-reg-in"/>
  <button type="submit" class="btn-sec1-acc log-reg-btn">Login</button>
</form>
<a href="/signup">
  <button class="btn-sec2-pri3 log-reg-se-btn">don't have an account?</button>
</a>
</div>
</div>
<div class="r">
<img src="{% static 'assets/media/illustrations/Login.svg' %}" alt="">
</div>
</div>
{% endblock  %}

templates/nav.html
{% block nav %}
<nav>
  <ul>
    <li>
      <a href="/" class="left nav-1 nav-item"> home </a>
    </li>
    <li>
      <a href="/view-rooms/" class="left nav-2 nav-item"> view rooms </a>
    </li>
    <li><a href="/" class="title"> Book It </a></li>
    {% if user.is_authenticated %}
    <li class="right nav-3 nav-item">
     Welcome {{request.user.name}}
    </li>
    <li>
      <a href="/logout/" class="right nav-4 nav-item"> logout</a>
    </li>
    {% else %}
    <li>
      <a href="/login/" class="right nav-3 nav-item"> login </a>
    </li>
    <li>
      <a href="/signup/" class="right nav-4 nav-item"> signup </a>
    </li>
    

    {% endif %}
  </ul>
</nav>
{% endblock %}

templates/seller/add-room.html
{% extends 'base.html' %} 
{% load static %}
{% block addroom %}
<div class="add-room">
  <div class="l">
    <div class="log-reg-tit upca add-room-tit">Add Room</div>
    <div class="in-card">
      <form action="/handleRoom/" method="POST" class="log-reg-form add-room-form">
        {% csrf_token %}
        <label for="room_size">Size</label>
        <input
          type="text"
          id="room_size"
          name="room_size"
          placeholder="Enter Size For The Place"
          required
          class="log-reg-in"
        />
        <label for="image">Image Link</label>
        <input
          type="text"
          id="image"
          name="image"
          placeholder="Enter Image Link Here"
          required
          class="log-reg-in"
        />
        <label for="address">Address</label>
        <input
          type="text"
          id="address"
          name="address"
          placeholder="Enter Address Here"
          required
          class="log-reg-in"
        />
        <label for="city">City</label>
        <input
          type="text"
          id="city"
          name="city"
          placeholder="Enter City"
          required
          class="log-reg-in"
        />
        <label for="rate">Rate</label>
        <input
          type="number"
          id="rate"
          name="rate"
          placeholder="Enter Rate"
          required
          class="log-reg-in"
        />
        <label for="floor">Floor</label>
        <input
          type="text"
          id="floor"
          name="floor"
          placeholder="Enter Floor Of Place"
          required
          class="log-reg-in"
        />
        <label for="furnishing">Furnishing</label>
        <input
          type="text"
          id="furnishing"
          name="furnishing"
          placeholder="Enter State Of Furnishing"
          required
          class="log-reg-in"
        />
        <label for="area">Area</label>
        <input
          type="text"
          id="area"
          name="area"
          placeholder="Enter Area In Sq.Ft."
          required
          class="log-reg-in"
        />
        <label for="parking">Parking</label>
        <input
          type="text"
          id="parking"
          name="parking"
          placeholder="Enter State Of Parking"
          required
          class="log-reg-in"
        />
        <label for="description">Description</label>
        <textarea name="description" id="description"class="log-reg-in"></textarea>
        <button type="submit" class="btn-sec1-acc log-reg-btn">Add</button>
      </form>
    </div>
  </div>
  <div class="r">
    <img src="{% static 'assets/media/illustrations/room.svg' %}" />
  </div>
</div>
{% endblock %}

templates/seller/seller.html
{% extends 'base.html' %}
{% block seller %}
    <div class="seller-con">
      <img src="https://images.unsplash.com/photo-1607152571560-ac7611d9abfe?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1964&q=80G0DqpsRQRoc" alt="seller image" class="seller-img" />
      <div class="sel-det">
      <h1 class="seller-name">{{seller.name}}</h1>
      <h2 class="seller-name">{{seller.contact}}</h2>
      <a href="mailto:{{seller.email}}">
      <h3 class="seller-name">{{seller.email}}</h3>
      </a>
      </div>
      <a href="tel:+91{{seller.contact}}">
      <button class="btn-acc-pri1 seller-call">call him!</button>
      </a>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block signup %}
<div class="reg">
<div class="l">
<div class="log-reg-tit upca">
signup
</div>
<div class="in-card">
<form action="/handleSignup/" method="POST" class="log-reg-form reg-form">
{% csrf_token %}
  <label for="name">Name</label>
  <input type="text"  id="name" name="name" placeholder="Enter Your Name Here" required class="log-reg-in"/>
  <label for="email">Email</label>
  <input type="email"  id="email" name="email" placeholder="Enter Your E-Mail Here" required class="log-reg-in"/>
  <label for="contact">Contact No.</label>
  <input type="tel"  id="contact" name="contact" placeholder="Enter Your Contact No. Here" required class="log-reg-in"/>
  <label for="">Account Type</label>
  <div class="ac-type">
  <input type="radio" name="ac-type" value="buyer" class="ac-type" checked="checked">Buyer
  <input type="radio" name="ac-type" value="seller" class="ac-type">Seller
  </div>
  <label for="pass">Password</label>
  <input type="password"  id="pass" name="pass" placeholder="Enter Password" required class="log-reg-in"/>
  <label for="pass2"> Confirm Password</label>
  <input type="password"  id="pass2" name="pass2" placeholder="Confirm Password" required class="log-reg-in"/>
  <button type="submit" class="btn-sec1-acc log-reg-btn">Signup</button>
</form>
<a href="/login">
  <button class="btn-sec2-pri3 log-reg-se-btn reg-se-btn">already have an account?</button>
</a>
</div>
</div>
<div class="r">
<img src="{% static 'assets/media/illustrations/Signup.svg' %}" alt="">
</div>
</div>
 {% endblock %}

templates/user/room.html
{% extends 'base.html' %}
{% block room %}
  <div class="room-det-upper">
  <div class="room-det-up-left">
    <img
      src="{{room.image}}"
      class="room-det-thumb"
    />
  </div>
  <div class="room-det-up-right">
    <div class="room-det-size">{{room.room_size}}</div>
    <div class="room-det-address">{{room.address}}</div>
    <div class="room-price-con">
      <div class="room-det-price">Rs.{{room.rate}}</div>
      <div class="room-det-rate">/month</div>
    </div>
    <div class="room-det-area">{{room.area}} sq.ft</div>
    <a href="{% url 'rooms:seller' room.seller_id %}">

    <button class="btn-acc-pri1 room-det-contact">Contact Seller</button>
    </a>
  </div>
  </div>
  <div class="room-det-lower">
    <div class="room-det-over">
    <h1>overview</h1>
    <div class="room-det-over-cont room-det-contr">
      <div class="room-det-over-cont-l">
        <div class="room-det-over-city room-det-over-vl">
          <h3>city:</h3>
          <p>{{room.city}}</p>
        </div>
        <div class="room-det-over-rate room-det-over-vl">
          <h3>rate:</h3>
          <p>{{room.rate}}</p>
        </div>
        <div class="room-det-over-floor room-det-over-vl">
          <h3>floor:</h3>
          <p>{{room.floor}}</p>
        </div>
      </div>
      <div class="room-det-over-cont-r">
        <div class="room-det-over-fur room-det-over-vl">
          <h3>furnishing:</h3>
          <p>{{room.furnishing}}</p>
        </div>
        <div class="room-det-over-area room-det-over-vl">
          <h3>area:</h3>
          <p>{{room.area}}Sq.Ft</p>
        </div>
        <div class="room-det-over-park room-det-over-vl">
          <h3>parking:</h3>
          <p>{{room.parking}}</p>
        </div>
      </div>
    </div>
    </div>
    <div class="room-det-des room-det-contr">
      <h1>description</h1>
      <p>
        {{room.description}}
      </p>
    </div>
    <div class="room-det-sel room-det-contr">
      <h1>seller</h1>
      <div class="room-det-sel-cont">
        <div class="room-det-sel-name">{{user.name}}</div>
        <a href="{% url 'rooms:seller' room.seller_id %}">
        <button class="btn-acc-pri1 room-det-contact">Contact Seller</button>
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/user/view-rooms.html
{% extends 'base.html' %}
{% load static %}
{% block rooms %}
<div class="rooms">
{% if rooms %}
{% for room in rooms %}
  <div class="room">
    <div class="room-left">
      <img
        src="{{room.image}}"
        class="room-img"
      />
    </div>
    <div class="room-right">
      <div class="room-row-1">
        <div class="room-city-con">
          <div class="room-city">city:</div>
          <div class="room-city-name">{{room.city}}</div>
        </div>
        <div class="room-price-con">
          <div class="room-price">Rs.{{room.rate}}</div>
          <div class="room-rate">/month</div>
        </div>
      </div>
      <div class="room-row-2">
        <div class="room-size">{{room.room_size}}</div>
        <div class="room-at">at</div>
        <div class="room-address">{{room.address}}</div>
      </div>
      <div class="room-row-3">
        <a href="{% url 'rooms:seller' room.seller_id %}">
          <button class="btn-acc-sec1 room-contact">Contact Seller</button>
        </a>
        <a href="{% url 'rooms:room' room.room_id%}">
        <button class="btn-acc-sec1 room-view-detials">View Details</button>
        </a>
      </div>
    </div>
  </div>

  
{% endfor %}
{% else %}
<div class="room-at">No Rooms Here</div>
{% endif %}
</div>
{% endblock %}